# This is a basic workflow to help you get started with Actions

name: OntoStackPush

# Controls when the action will run.

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sheet2rdf:
    # The type of runner that the job will run on
    
    name: OntoStackPush
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2    
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.8"
      - name: Prepare
        shell: bash -l {0}   
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          conda install requests
      
      - name: deploy-to-OntoStack
        env:
          FILE_NAME: ${{secrets.FILE_NAME}}
          GRAPH: ${{secrets.GRAPH}}
          DB_PASS: ${{secrets.DB_PASS}}
          DB_USER: ${{secrets.DB_USER}}
          SPARQL_ENDPOINT: ${{secrets.SPARQL_ENDPOINT}}
          IADOPT_CFG: ${{secrets.IADOPT_CFG}}
          TTL_URL: ${{secrets.TTL_URL}}
        run: |
          python ./src/cfg.py        
          ./src/deploy2db.sh
